config/routes.rb
Multiverso::Application.routes.draw do
 

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :histories, :publications
  get "/continue_publication" => "publications#continue_publication"
  get "/more_publications" => "publications#more_publications"
  post "/continue_publication/new" => "publications#create_continue_publication"
  get "/search" => "publications#search"
  get "/banned_user" => "publications#banned_user"
  get "/singularities" => "publications#singularities"
  get "/show_history_continuation" => "histories#show_history_continuation"
  post "/show_history_continuation/continue_with_posted_publication" => "histories#continue_with_posted_publication"
  get "/show_history_include_publication" => "histories#show_history_include_publication"

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  root to: "publications#index"
  

 end

app/models/publication.rb
class Publication < ActiveRecord::Base
  belongs_to :user
  has_many :histories, foreign_key: "publication_id"
  has_many :publications_and_histories
  self.inheritance_column = nil


 before_save do
  if self.type == 2
    if self.url.match(/\b658px\b/)
      self.url["658"]="300"
    end
  end
  if self.type==3
    if self.url.match(/\b600\b/) 
      self.url["600"]= "300"
      self.url["600"]= "300"
    end
    if self.url.match(/\b480\b/)
      self.url["480"]= "300"
      self.url["480"]= "300"
    end
    if self.url.match(/\b320\b/)
      self.url["320"]= "300"
      self.url["320"]= "300"
    end
  end
end

def self.checkNewHistory(history_id,llink)
  if(history_id == "-1")
    return true
  else
    @p_and_h= PublicationsAndHistory.where("history_id = #{history_id} AND publication_id = #{llink}")
    @p_and_h.each do |publ|
      if publ.rlink_id != nil
        return true
      end
    end
    return false
  end
end

def self.delete_from_p_h(publication)
  if(!publication.singularity)
    @p_and_h = PublicationsAndHistory.find_all_by_publication_id publication.id
    @p_and_h.each do |publ|
      publication = Publication.find_by_id publ.publication_id
        if(!publ.rlink_id.nil?)
          temp_llink = PublicationsAndHistory.where("history_id = ? AND publication_id = ?","#{publ.history_id}","#{publ.llink_id}")
          temp_rlink = PublicationsAndHistory.where("history_id = ? AND publication_id = ?","#{publ.history_id}","#{publ.rlink_id}")
          temp_llink[0].rlink_id = publ.rlink_id
          temp_rlink[0].llink_id = publ.llink_id
          temp_llink[0].save
          temp_rlink[0].save
          PublicationsAndHistory.delete(publ.id)
        else
          temp_llink = PublicationsAndHistory.where("history_id = ? AND publication_id = ?","#{publ.history_id}","#{publ.llink_id}")
          temp_llink[0].rlink_id =nil
          temp_llink[0].save
          PublicationsAndHistory.delete(publ.id)
        end
      end
  else
    #si borra singularidad borra todas las historias asociadas y todas las historia-publicacion
    PublicationsAndHistory.delete_all(["llink_id = ? OR publication_id = ?","#{publication.id}","#{publication.id}"])
    History.delete_all(["publication_id = ?", "#{publication.id}"])
  end
end

def stories_which_belongs
 PublicationsAndHistory.where("publication_id = #{self.id}")
end



def self.create_publications_and_histories(history_id,llink,publication_id,history_name)
  inHistory = 0
  if(history_id == "-1")
    @n_history= History.new
    @n_history.title = history_name
    @n_history.publication_id = llink
    @n_history.save
    @n_ph = PublicationsAndHistory.new
    @n_ph.publication_id = llink
    @n_ph.history_id = @n_history.id
    @n_ph2 = PublicationsAndHistory.new
    @n_ph2.llink_id = llink
    @n_ph2.publication_id = publication_id
    @n_ph2.history_id = @n_history.id
    @n_ph.rlink_id=publication_id
    @n_ph.save
    @n_ph2.save
    inHistory = @n_history.id
  else
    @p_and_h= PublicationsAndHistory.where("history_id = #{history_id} AND publication_id = #{llink}")
    @p_and_h.each do |publ|
      if publ.rlink_id == nil
        publ.rlink_id = publication_id
        publ.save
        @n_ph = PublicationsAndHistory.new
        @n_ph.llink_id = llink
        @n_ph.publication_id = publication_id
        @n_ph.history_id = history_id
        inHistory = history_id
        @n_ph.save
      else
        puts "its not nill i must create a new history omg with publication #{publication_id}"
        @n_history= History.new
        @n_history.title = history_name
        @temp_history = History.find(history_id)
        @n_history.publication_id = @temp_history.publication_id
        @n_history.save
        inHistory = @n_history.id
        @n_ph= PublicationsAndHistory.where("history_id = #{history_id}")
        @n_ph.each do |posts|
          @temp_ph = PublicationsAndHistory.new
          @temp_ph.history_id = @n_history.id
          if(posts.publication_id == Integer(llink))
            @temp_ph.llink_id = posts.llink_id
            @temp_ph.publication_id = posts.publication_id
            @temp_ph.rlink_id = publication_id
            @temp_ph.save
            @temp_ph = PublicationsAndHistory.new
            @temp_ph.llink_id = llink
            @temp_ph.publication_id = publication_id
            @temp_ph.history_id = @n_history.id
            @temp_ph.save
            break
          else
            @temp_ph.rlink_id = posts.rlink_id
            @temp_ph.llink_id = posts.llink_id
            @temp_ph.publication_id = posts.publication_id
            @temp_ph.save
          end
        end
      end
    end
  end
  return inHistory
end

end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: [:show, :edit, :update, :destroy]
   respond_to :html, :xml, :json

  def index
    @publications = Publication.order("updated_at desc").page(params[:page]).per(15)
    @histories = History.order('id DESC').limit(5)
    @singularity = History.first
    respond_with(@publications)
  end

  def show
    puts @publication.stories_which_belongs
    respond_with(@publication)
  end

  def singularities
    @publications = Publication.find_all_by_singularity true
  end

  def continue_publication
    @history_id = params[:history_id]
    @llink = params[:llink]
    @generatesHistory = Publication.checkNewHistory(@history_id,@llink)
    @publication = Publication.new
    respond_with(@publication)
  end

  def create_continue_publication
    @publication = Publication.new(publication_params)
    @publication.user_id = current_user.id
    @publication.singularity = false
    @publication.save
    @history_id = params[:history_id]
    @llink = params[:llink]
    @history_name = params[:history_name]
    if @history_name ==nil
      @history_name = "Historia sin nombre"
    end
    Publication.create_publications_and_histories(@history_id,@llink,@publication.id,@history_name)
    respond_with(@publication)
  end

  def search
    search_params = params[:search]
    @publications = Publication.where("content LIKE ? OR url LIKE ?","%#{search_params}%","%#{search_params}%")
  end

  def new
    @publication = Publication.new
    respond_with(@publication)
  end

  def edit
  end

  def create
    @publication = Publication.new(publication_params)
    @publication.user_id = current_user.id
    if(current_user.admin)
      @publication.singularity = true
    else
      @publication.singularity = false
    end
    @publication.save
    respond_with(@publication)
  end


  def update
    @publication.update(publication_params)
    respond_with(@publication)
  end

  def destroy
    Publication.delete_from_p_h(@publication)
    @publication.destroy
    respond_with(@publication)
  end

  def more_publications
    @publications = Publication.order("updated_at desc").page(params[:page]).per(15)
    respond_to do |format|
      format.json { render :json => @publications }
    end
  end

  def banned_user
  end

  private
    def set_publication
      @publication = Publication.find(params[:id])
    end

    def publication_params
      params.require(:publication).permit(:content, :url, :user_id, :type, :singularity)
    end

end

app/views/publications/_form.html.erb
<%= form_for(@publication) do |f| %>
  <% if @publication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
      <% @publication.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br>
    <%= f.select :type, options_for_select([["Texto", "1"], ["Instagram", "2"],  ["Vine", "3"] ]),  {:prompt => 'Selecciona el tipo de tu publicación'} %>
  </div>
  <div class="field" id="content" style="display: none">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field" id="url" style="display: none">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <%= hidden_field_tag :history_id, @history_id, :id => "history_id" %>
  <%= hidden_field_tag :llink, @llink, :id => "llink" %>
  <div class="actions">
    <%= f.submit %>

  </div>
<% end %>

<%= javascript_include_tag "hide_content_url" %>

app/views/publications/_publication.html.erb
  <hr>
  <div class="row">
    <div class="columns large-9 medium-6">
      <blockquote>
      <% if publication.content == "" %>
       <%= link_to content_tag('div',"Ver Publicación"), publication %>
        <%= raw publication.url %>
      <% else %> 
        <%= link_to content_tag('h3',publication.content), publication %>
      <% end %>
      <cite><%= publication.user.name %> - <em><%= time_ago_in_words(publication.created_at) %> ago</em></cite>
      </blockquote>  
    </div>
    <!-- <div class="columns large-3 medium-6">
      <ul class="inline-list">
        <li><%= link_to 'Destroy', publication, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      </ul>
    </div> -->
  </div>

app/views/publications/banned_user.html.erb
<h1> Usuario Bloqueado </h1>
<p>Contacte a el Administrador.</p>

app/views/publications/continue_publication.html.erb
<%= javascript_include_tag "hide_content_url" %>
<div class="row">
<h1>Continuar publicación</h1>
<%= form_for(@publication, url: continue_publication_new_path) do |f| %>
  <% if @publication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
      <% @publication.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br>
    <%= f.select :type, options_for_select([["Texto", "1"], ["Instagram", "2"],  ["Vine", "3"] ]),  {:prompt => 'Selecciona el tipo de tu publicación'} %>
  </div>
  <div class="field" id="content" style="display: none">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field" id="url" style="display: none">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <%= hidden_field_tag :history_id, @history_id, :id => "history_id" %>
  <%= hidden_field_tag :llink, @llink, :id => "llink" %>

  <% if @generatesHistory %>
  <%= label_tag("Esta continuacion generará una nueva historia, deberas colocarle un nombre!") %>
  <%= text_field_tag("history_name")%>  
  <% end %>

  <div class="actions">
    <%= f.submit %>

  </div>
<% end %>
</div>

app/views/publications/edit.html.erb
<h1>Editing publication</h1>

<%= render 'form' %>

<%= link_to 'Show', @publication %> |
<%= link_to 'Back', publications_path %>

app/views/publications/index.html.erb
<body>



<div id="headerblue"></div>
<div id="super_wrapper">
  <div id="wrappercontent">
    <div id="singularidad">
      <div id="titulo_singularidad"><%= @singularity.title %></div>
      <div id="singularidad_texto"><%= @singularity.publication.content %> <% if user_signed_in?  %> <%= link_to 'Crea tu propia historia!', continue_publication_path(:history_id =>"-1", :llink => @singularity.id) %><%end%></div>

    </div>
  
        <div id="pills">
      <div id="date"><%= time_ago_in_words(@publications[0].created_at) %></div>
      <div id="pillscontent"><% if @publications[0].content == "" %>
       <%= link_to content_tag('div',"Ver Publicación"), @publications[0] %>
        <%= raw @publications[0].url %>
      <% else %> 
        <%= link_to content_tag('pillscontent',@publications[0].content), @publications[0] %>
      <% end %></div>
      <div id="continuar">Por: <%=@publications[0].user.name %></div>
    </div>
     <div id="pills_2">
      <div id="date_2"><%= time_ago_in_words(@publications[1].created_at) %></div>
      <div id="pillscontent_2"><% if @publications[1].content == "" %>
       <%= link_to content_tag('div',"Ver Publicación"), @publications[1] %>
        <%= raw @publications[1].url %>
      <% else %> 
        <%= link_to content_tag('pillscontent_2',@publications[1].content), @publications[1] %>
      <% end %></div>
      <div id="continuar_2">Por: <%=@publications[1].user.name %></div>
    </div>
    <div id="pills_3">
      <div id="date_3"><%= time_ago_in_words(@publications[2].created_at) %></div>
      <div id="pillscontent_3"><% if @publications[2].content == "" %>
       <%= link_to content_tag('div',"Ver Publicación"), @publications[2] %>
        <%= raw @publications[2].url %>
      <% else %> 
        <%= link_to content_tag('pillscontent_2',@publications[2].content), @publications[2] %>
      <% end %></div>
      <div id="continuar_3">Por: <%=@publications[2].user.name %></div>

     </div>
 </div>
 <div id="down_wrapper">
  <div id="pills_4">
      <div id="date_4"><%= time_ago_in_words(@publications[3].created_at) %></div>
      <div id="pillscontent_4"><% if @publications[3].content == "" %>
       <%= link_to content_tag('div',"Ver Publicación"), @publications[3] %>
        <%= raw @publications[3].url %>
      <% else %> 
        <%= link_to content_tag('pillscontent_2',@publications[3].content), @publications[3] %>
      <% end %></div>
      <div id="continuar_4">Por: <%=@publications[3].user.name %></div>
      </div>
      
       <div id="pills_5">
      <div id="date_5"><%= time_ago_in_words(@publications[4].created_at) %></div>
      <div id="pillscontent_5"><% if @publications[4].content == "" %>
       <%= link_to content_tag('div',"Ver Publicación"), @publications[4] %>
        <%= raw @publications[4].url %>
      <% else %> 
        <%= link_to content_tag('pillscontent_2',@publications[4].content), @publications[4] %>
      <% end %></div>
      <div id="continuar_5">Por: <%=@publications[4].user.name %></div>
      </div>
      
       <div id="pills_6">
      <div id="date_6"><%= time_ago_in_words(@publications[5].created_at) %></div>
      <div id="pillscontent_6"><% if @publications[5].content == "" %>
       <%= link_to content_tag('div',"Ver Publicación"), @publications[5] %>
        <%= raw @publications[5].url %>
      <% else %> 
        <%= link_to content_tag('pillscontent_2',@publications[5].content), @publications[5] %>
      <% end %></div>
      <div id="continuar_6">Por: <%=@publications[5].user.name %></div>
      </div>
      

 
 
 
 </div> 
  
</div>






</body>

app/views/publications/index.json.erb
$("#publications").append("<%= escape_javascript(render(@publications)) %>");

app/views/publications/new.html.erb
<h1>New publication</h1>

<%= render 'form' %>

<%= link_to 'Back', publications_path %>

app/views/publications/search.html.erb
<% @publications.each do |publication|%>
  <hr>
  <div class="row">
    <div class="columns large-9 medium-6">
      <blockquote>
      <% if publication.content == "" %>
        <%= raw publication.url %>
      <% else %> 
        <%= link_to content_tag('h3',publication.content), publication %>
      <% end %>
      <cite><%= publication.user.name %> - <em><%= time_ago_in_words(publication.created_at) %> ago</em></cite>
      </blockquote>
      
        
      
    </div>

    <div class="columns large-3 medium-6">
      <ul class="inline-list">
        <% if user_signed_in?  %><% if current_user.admin  %><li><%= link_to 'Destroy', publication, method: :delete, data: { confirm: 'Are you sure?' } %></li><%end%><%end%>
      </ul>
    </div>
  </div>
<% end %>

app/views/publications/show.html.erb
<%= stylesheet_link_tag "post_view_style.css", media: "all" %>
<p id="notice"><%= notice %></p>
<!--
<div class="row">
  <div class="large-6 large-centered columns">
    <div class="panel callout radius">
      <% if @publication.type >1 %>
        <center><%= raw @publication.url%></center>
      <%else%>
        <center><p><h3><%= @publication.content %></h3></p></center>
      <%end%>
      <center><cite><%= @publication.user.name %> - <em><%= time_ago_in_words(@publication.created_at) %> ago</em></cite><br>
        <% if !@publication.singularity && user_signed_in? %> 
          <%= link_to 'Úsala en otra historia!', :controller =>"histories", :action => "show_history_continuation", :publication_id => @publication.id %>
        <%end%>
      </center>
      Ver también en:
      <ul class="breadcrumbs">
        <%@publication.stories_which_belongs.each do |history|%>

          <li><a href="/histories/<%=history.history_id%>"><%= history.history.title %></a></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
-->



<div id="headerblue"></div>
<div id="wrapper">
  <div id="upper">
    <div id="pills">
      <div id="date">Fecha de Publicacion</div>
      <div id="pillscontent"><% if @publication.type >1 %>
        <center><%= raw @publication.url%></center>
      <%else%>
        <center><p><h3><%= @publication.content %></h3></p></center>
      <%end%>
      </div>
      <div id="continuar">Por: <%=@publication.user.name%></div>
      <div id="pillsuser">Continuar????</div>
    </div>
  </div>
  <div id="mini_wrap">
    <div id="opcion_1">
      <div>
          <% if !@publication.singularity && user_signed_in? %> 
            <%= link_to 'Úsala en otra historia!', :controller =>"histories", :action => "show_history_continuation", :publication_id => @publication.id %>
            <%end%>
      </div>
    </div>
       <div id="opcion_2">
         <div id="wite_box_opcion_2">
           <ul class="breadcrumbs">
              <%@publication.stories_which_belongs.each do |history|%>

              <li><a href="/histories/<%=history.history_id%>"><%= history.history.title %></a></li>
            <% end %>
        </ul>
       </div>
       </div>
  </div>
</div>

app/views/publications/singularities.html.erb
<h2>Singularidades</h2>
<% @publications.each do |publication|%>
  <hr>
  <div class="row">
    <div class="columns large-9 medium-6">
      <blockquote>
      <% if publication.content == "" %>
        <%= raw publication.url %>
      <% else %> 
        <%= link_to content_tag('h3',publication.content), publication %>
      <% end %>
      <cite><%= publication.user.name %> - <em><%= link_to time_ago_in_words(publication.created_at), publication %> ago</em></cite>
      </blockquote>
    </div>

    <div class="columns large-3 medium-6">
      <ul class="inline-list">
        <% if user_signed_in?  %><li><%= link_to ' Continuar', continue_publication_path(:history_id =>-1, :llink => publication.id) %><% if current_user.admin  %> | <%= link_to 'Destroy', publication, method: :delete, data: { confirm: 'Are you sure?' } %></li><%end%><%end%>
      </ul>
    </div>
  </div>
<% end %>