config/routes.rb
Multiverso::Application.routes.draw do
 

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :histories, :publications
  get "/continue_publication" => "publications#continue_publication"
  get "/more_publications" => "publications#more_publications"
  post "/continue_publication/new" => "publications#create_continue_publication"
  get "/search" => "publications#search"
  get "/banned_user" => "publications#banned_user"
  get "/singularities" => "publications#singularities"
  get "/show_history_continuation" => "histories#show_history_continuation"
  post "/show_history_continuation/continue_with_posted_publication" => "histories#continue_with_posted_publication"
  get "/show_history_include_publication" => "histories#show_history_include_publication"

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  root to: "publications#index"
  

 end

app/models/history.rb
class History < ActiveRecord::Base
  belongs_to :publication, foreign_key: "publication_id"
  has_many :publications_and_histories

  def self.publications_from_history(history)
	p_and_h= PublicationsAndHistory.find_all_by_history_id history.id
    publications = Array.new()
    #publications.push(Publication.find_by_id p_and_h[0].llink_id)
    p_and_h.each do |publ|
      publications.push(Publication.find_by_id publ.publication_id)
    end
    return publications
  end

  def self.histories_without_publication(publication_id)
  	histories = Array.new()
    histories_to_exclude = Array.new()
    p_and_h= PublicationsAndHistory.find_all_by_publication_id publication_id
    p_and_h.each do |post|
      if(!histories_to_exclude.include? post.history.id)
        histories_to_exclude.push(post.history.id)
      end
    end

    histories=History.where("id NOT IN (?)", histories_to_exclude)
    return histories

  end


end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_history, only: [:show, :edit, :update, :destroy]
  respond_to :html, :xml, :json
  def index
    @histories = History.all
    respond_with(@histories)
  end

  def show
    @publications = History.publications_from_history(@history)
    respond_with(@history)
  end

  def new
    if user_signed_in?
      @history = History.new
      respond_with(@history)
    else
      redirect_to root_path
    end
  end

  def edit
    unless user_signed_in?
      redirect_to root_path
    end
  end

  def show_history_continuation
    @publication_id = params[:publication_id]
    @history_id = params[:history_id]
    @histories = History.histories_without_publication(@publication_id)

    if(@history_id == nil)
      @history_id = @histories[0].id
    end

    @publications = History.publications_from_history(History.find_by_id @history_id)
  end

  def continue_with_posted_publication
    @history_id = params[:history_id]
    @llink = params[:llink]
    @publication_id = params[:publication]
    actual_history_id=Publication.create_publications_and_histories(@history_id,@llink,@publication_id)
    redirect_to history_url(actual_history_id)
  end

  def show_history_include_publication
    @publication_id = params[:publication_id]
    @history_id = params[:history_id]
    @histories = History.histories_with_publication(@publication_id)

    if(@history_id == nil)
      @history_id = @histories[0].id
    end

    @publications = History.publications_from_history(History.find_by_id @history_id)
  end

  def create
    @history = History.new(history_params)
    @history.save
    respond_with(@history)
  end

  def update
    @history.update(history_params)
    respond_with(@history)
  end

  def destroy
    PublicationsAndHistory.delete_all(["history_id = ?","#{@history.id}"])
    @history.destroy
    respond_with(@history)
  end

  private
    def set_history
      @history = History.find(params[:id])
    end

    def history_params
      params.require(:history).permit(:publication_id)
    end
end

app/views/histories/_form.html.erb
<%= form_for(@history) do |f| %>
  <% if @history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@history.errors.count, "error") %> prohibited this history from being saved:</h2>

      <ul>
      <% @history.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :publication_id %><br>
    <%= f.text_field :publication_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/histories/edit.html.erb
<h1>Editing history</h1>

<%= render 'form' %>

<%= link_to 'Show', @history %> |
<%= link_to 'Back', histories_path %>

app/views/histories/index.html.erb
<h1></h1>

<table>
  <thead>
    <tr>
      <th>Singularidad</th>
      <th>Fecha</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @histories.each do |history| %>
      <tr>
        <td><%= truncate(history.title,length: 100) %></td>
        <td><%= history.created_at.to_formatted_s(:short) %></td>
        <td><%= link_to 'Ver Historia', history %></td>
        <% if user_signed_in? && current_user.admin?%>
          <td><%= link_to 'Destroy', history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/histories/new.html.erb
<h1>New history</h1>

<%= render 'form' %>

<%= link_to 'Back', histories_path %>

app/views/histories/show.html.erb
<p id="notice"><%= notice %></p>
<p><strong><h3><%= @history.title %></h3></strong></p>
<table>
  <tbody>
    <% @publications.each do |publication| %>
      <hr>
    	<div class="row">
    		<div class="columns large-9 medium-6">
    			<blockquote>
    				<% if publication.type != 1 %>
      			<%= raw publication.url %>
    				<% else %>
      			<%= link_to content_tag('h3',publication.content), publication %>
    				<% end %>
    				<cite><%= publication.user.name %> - <em><%= time_ago_in_words(publication.created_at) %> ago</em></cite>
    			</blockquote>
    	  </div>
        <div class="columns large-3 medium-6">
          <ul class="inline-list">
            <li> <% if user_signed_in?  %> <%= link_to ' Continuar', continue_publication_path(:history_id =>@history.id, :llink => publication.id) %><% if !publication.singularity %> <%= link_to 'Usar como continuacion', :controller =>"histories", :action => "show_history_continuation", :publication_id => publication.id %><%end%><%end%></li>
          </ul>
        </div>
      </div>
    <% end %>
  </tbody>
</table>

<!--
<%= link_to 'Edit', edit_history_path(@history) %> |
<%= link_to 'Back', histories_path %> -->

app/views/histories/show_history_continuation.html.erb
Barra de historias: <% @histories.each do |history| %>
<%= link_to history.id, show_history_continuation_path(:history_id => history.id, :publication_id => @publication_id) %>
<% end %>
<table>
  <tbody>
    <% @publications.each do |publication| %>
      <hr>
    	<div class="row">
    		<div class="columns large-9 medium-6">
    			<blockquote>
    				<% if publication.type != 1 %>
      			<%= raw publication.url %>
    				<% else %>
      			<%= link_to content_tag('h3',publication.content), publication %>
    				<% end %>
    				<cite><%= publication.user.name %> - <em><%= time_ago_in_words(publication.created_at) %> ago</em></cite>
    			</blockquote>
    	  </div>
        <div class="columns large-3 medium-6">
          <ul class="inline-list">
            <li><% if user_signed_in? %> <%= link_to ' Continuar', show_history_continuation_continue_with_posted_publication_path(:history_id =>@history_id, :llink => publication.id, :publication => @publication_id), :method => :post %><%end%></li>
          </ul>
        </div>
      </div>
    <% end %>
  </tbody>
</table>

app/views/histories/show_history_include_publication.html.erb
Barra de historias: <% @histories.each do |history| %>
<%= link_to history.id, show_history_include_publication_path(:history_id => history.id, :publication_id => @publication_id) %>
<% end %>
<table>
  <tbody>
    <% @publications.each do |publication| %>
      <hr>
    	<div class="row">
    		<div class="columns large-9 medium-6">
    			<blockquote>
    				<% if publication.type != 1 %>
      			<%= raw publication.url %>
    				<% else %>
      			<%= link_to content_tag('h3',publication.content), publication %>
    				<% end %>
    				<cite><%= publication.user.name %> - <em><%= time_ago_in_words(publication.created_at) %> ago</em></cite>
    			</blockquote>
    	  </div>
        <div class="columns large-3 medium-6">
          <ul class="inline-list">
            <li><% if user_signed_in? %><%= link_to ' Continuar', continue_publication_path(:history_id =>@history_id, :llink => publication.id) %><%end%></li>
          </ul>
        </div>
      </div>
    <% end %>
  </tbody>
</table>